fix(report-portal): Fixed search for projects page
appdev-platform/janus-backstage-plugins pull request #3
Opened 2024-05-06 11:46 UTC by yashoswalyo

- Added request to add button on instances page

![image](https://github.com/appdev-platform/janus-backstage-plugins/assets/42431299/8331a29f-0f2a-44ee-b2e7-2cb6ab185b37)
- Updated readme
- Changed breadcrums color to white
  
![image](https://github.com/appdev-platform/janus-backstage-plugins/assets/42431299/b50e7974-6903-46f5-96ae-c86c6f11f549)

2024-05-06 11:48 UTC, yashoswalyo commented
Email template
![image](https://github.com/appdev-platform/janus-backstage-plugins/assets/42431299/0df69c11-9df9-4ac4-a590-401441d22783)

2024-05-06 12:29 UTC, deshmukhmayur requested changes

2024-05-06 12:29 UTC, deshmukhmayur commented on plugins/report-portal/src/components/ReportPortalGlobalPage/ReportPortalGlobalPage.tsx
> +              )}&su=Request%20to%20add%20a%20report%20portal%20instance&body=Requesting%20to%20add%20a%20new%20Report%20Portal%20instance%20to%20Red%20Hat%20Experience%20Platform.%0A%0AHostname%3A%0A
@yashoswalyo I think the email subject and body should be stored in a string variable first.

```ts
const body = encodeURIComponent(`<multiline
email body>
`);
```

2024-05-06 12:58 UTC, yashoswalyo commented on plugins/report-portal/src/components/ReportPortalGlobalPage/ReportPortalGlobalPage.tsx
> +              )}&su=Request%20to%20add%20a%20report%20portal%20instance&body=Requesting%20to%20add%20a%20new%20Report%20Portal%20instance%20to%20Red%20Hat%20Experience%20Platform.%0A%0AHostname%3A%0A
done

2024-05-07 10:47 UTC, deshmukhmayur approved these changes
LGTM.

2024-05-07 10:49 UTC, deshmukhmayur commented
@yashoswalyo the yarn install step seems to be failing. Maybe because you've bumped up the report portal plugin version. 

Can you update the `yarn.lock`?

2024-05-08 05:27 UTC, yashoswalyo commented
Tests are failing even after adding `yarn.lock` file

2024-05-08 06:33 UTC, riginoommen commented
Try removing yarn.locak, nodemodules and try the tests

2024-05-08 08:30 UTC, riginoommen approved these changes

2024-05-08 08:30 UTC, merged